server:
  #  port 번호가 0번일 경우, 0~65535중에 현재 host에서 사용하지 않는 port 임의로 설정
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  config:
    activate:
      on-profile: local
  application:
    name: product-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordermsa
    username: root
    password: test1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  redis:
    host: localhost
    port: 6379

  kafka:
    kafka-server: localhost:9092
    consumer:
#      카프카에서 그룹id는 컨슈머 그룹을 식별하는 id로서, 동일한 그룹id를 가진 컨슈머들은 메시지를 분담해서 consume
      group-id: product-group

logging:
  level:
    root: info

aws:
  credentials:
    access-key: xxx
    secret-key: yyy
  region: ap-northeast-2
  s3:
    bucket1: yun-board-profile-image

