apiVersion: v1
kind: Pod
metadata:
# pod의 이름은 네임스페이스내에서 유일해야함
  name: my-nginx1
  namespace: yun-ns 
  # labels는 service의 라우팅 대상이 되는 기준. 같은 label이 붙은 여러개의 pod 생성 가능.
  labels:
    app: my-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    # pod의 포트는 내부포트를 의미하고, 프로그램 자체의 포트와 동일
    - containerPort: 80