name: deploy order-backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout github
        uses: actions/checkout@v2
      
      - name: install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.25.9"
        id: install
        
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET }}
          aws-region: ap-northeast-2

      - name: update cluster infomation
        run: aws eks update-kubeconfig --name 1team-eks --region ap-northeast-2

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: apigateway build and push
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: yun-ns/apigateway
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./3.msa/apigateway/Dockerfile ./3.msa/apigateway
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: apigateway kubectl apply
        run: |
          kubectl apply -f ./3.msa/apigateway/k8s/depl_svc.yml
          kubectl rollout restart deployment apigateway-depl -n yun-ns

      - name: member build and push
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: yun-ns/member
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./3.msa/member/Dockerfile ./3.msa/member
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: member kubectl apply
        run: |
          kubectl apply -f ./3.msa/member/k8s/depl_svc.yml
          kubectl rollout restart deployment member-depl -n yun-ns

      - name: ordering build and push
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: yun-ns/ordering
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./3.msa/ordering/Dockerfile ./3.msa/ordering
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: ordering kubectl apply
        run: |
          kubectl apply -f ./3.msa/ordering/k8s/depl_svc.yml
          kubectl rollout restart deployment ordering-depl -n yun-ns

      - name: product build and push
        env:
          REGISTRY: 346903264902.dkr.ecr.ap-northeast-2.amazonaws.com
          REPOSITORY: yun-ns/product
          IMAGE_TAG: latest
        run: |
          docker build \
          -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
          -f ./3.msa/product/Dockerfile ./3.msa/product
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: product kubectl apply
        run: |
          kubectl apply -f ./3.msa/product/k8s/depl_svc.yml
          kubectl rollout restart deployment product-depl -n yun-ns

        