server:
  port: 8080

eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: api-gateway
  cloud:
    gateway:
      #      CORS 처리. 서비스모듈에서는 웹브라우저와 직접 통신하지 않으므로, cors처리 불필요.
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost:3000'
              - 'https://www.yuniee.store'
            allowedMethods: '*'
            allowedHeaders: '*'
            allowedCredentials: true
      routes:
        - id: member-service
          predicates:
            - Path=/member-service/**
          filters:
#            StripPrefix : 첫번째 접두어를 제거후에 member-service로 http요청 전달
            - StripPrefix=1
            # k8s의 서비스명을 사용
          uri: http://member-service
        - id: ordering-service
          predicates:
            - Path=/ordering-service/**
          filters:
            - StripPrefix=1
            # k8s의 서비스명을 사용
          uri: http://ordering-service
        - id: product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
            # k8s의 서비스명을 사용
          uri: http://product-service
jwt:
  secretKey: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
